language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pip install -r requirement.txt

script:
    - coverage run --source='tutotravisapp' manage.py test && coverage report && coverage html
after_success:
    - coveralls