language: python

python:
    - "3.7"
    - "3.8"
    - "3.9"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pipenv install

script:
    -  coverage run --source='tutotravisapp' manage.py test && coverage report && coverage html
after_success:
    - coveralls