language: python

python:
    - "3.7"
    - "3.8"
    - "3.9"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pip install -r requirement.txt

script:
    # -  coverage run --source='blog' manage.py test && coverage report && coverage html
    - python manage.py test



# after_success:
#     - coveralls
